version: "3.8"
services:
  app:
    build:
      context: .
      target: development
      dockerfile: ../../Dockerfiles/Flask_auth/Dockerfile
    image: ecom_authorization
    command: ["python", "-m","app"]
    environment:
      - PORT_APP=5000
      - SQLALCHEMY_USERNAME:pguser
      - SQLALCHEMY_PASSWORD:pgpassword
      - SQLALCHEMY_DATABASE_NAME:auth_db
      - JWT_SECRET_KEY=super-secret-key
      - TRACING_ENABLED=False
      - TRACING_AGENT_HOST_NAME=jaeger
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./src/app:/home/app/src/app
      - ./src/migrations:/home/app/src/migrations
      - "auth_api_logs:/home/app/src/logs"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started

  redis:
    image: redis:6-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 10

  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: ${SQLALCHEMY_USERNAME}
      POSTGRES_PASSWORD: ${SQLALCHEMY_PASSWORD}
      POSTGRES_DB: ${SQLALCHEMY_DATABASE_NAME}
    healthcheck:
      test: pg_isready -U ${SQLALCHEMY_USERNAME} -d ${SQLALCHEMY_DATABASE_NAME}
      interval: 5s
      timeout: 20s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"

  nginx:
    build: ../../nginx
    restart: always
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "5010:5010"  # auth_api
    depends_on:
      - app

volumes:
  redis-data:
    driver: "local"
  postgres-data:
    driver: "local"
  auth_api_logs:
  nginx_logs:

